window.GALLERY_DATA = [
  // Sports Designs
  { id:"s01", cat:"sports", label:"FUNAABSU League Board Committee", image:"images/sports-01.png", desc:"Official board committee announcement design for the FUNAABSU League.", wide:true, tall:false },
  { id:"s02", cat:"sports", label:"Predict Win Get Paid", image:"images/sports-02.png", desc:"Promotional ad design for a sports prediction campaign.", wide:false, tall:false },
  { id:"s03", cat:"sports", label:"FIFA World Cup 2026", image:"images/sports-03.png", desc:"FIFA World Cup 2026 social media post — bold, cinematic tournament branding.", wide:false, tall:false },
  { id:"s04", cat:"sports", label:"FUNAABSU League 2.0 Sponsors", image:"images/sports-04.png", desc:"Sponsors display graphic for FUNAABSU League 2.0.", wide:true, tall:false },
  { id:"s05", cat:"sports", label:"FUNAABSU × Sofascore Partnership", image:"images/sports-05.png", desc:"Partnership announcement graphic for FUNAABSU and Sofascore.", wide:false, tall:false },
  { id:"s06", cat:"sports", label:"Matchday 1 Fixture", image:"images/sports-06.png", desc:"Matchday 1 fixture card — dynamic layout with team details.", wide:false, tall:false },
  { id:"s07", cat:"sports", label:"FA Cup Final — Vortex vs Hydro FC", image:"images/sports-07.png", desc:"FA Cup Final matchday graphic: Vortex FC vs Hydro FC.", wide:false, tall:true },
  { id:"s08", cat:"sports", label:"SUG Olympics Final '26", image:"images/sports-08.png", desc:"Official finals poster for the SUG Olympics 2026.", wide:false, tall:false },
  { id:"s09", cat:"sports", label:"FUNAABSU League 2.0 Poster", image:"images/sports-09.png", desc:"Cinematic season poster for FUNAABSU League 2.0.", wide:true, tall:false },
  { id:"s10", cat:"sports", label:"NAAS FUNAAB vs FASA OOU", image:"images/sports-10.png", desc:"Inter-university matchday graphic — NAAS FUNAAB vs FASA OOU.", wide:false, tall:false },
  { id:"s11", cat:"sports", label:"SUG Olympics Games Lineup", image:"images/sports-11.png", desc:"Full games lineup graphic for the SUG Olympics.", wide:false, tall:false },
  { id:"s12", cat:"sports", label:"Eclipse United — Eid Mubarak", image:"images/sports-12.png", desc:"Eid Mubarak greeting graphic from Eclipse United FC.", wide:false, tall:false },
  { id:"s13", cat:"sports", label:"CYDASSA vs SENIFSSA Matchday", image:"images/sports-13.png", desc:"Matchday fixture card — CYDASSA vs SENIFSSA.", wide:false, tall:false },
  { id:"s14", cat:"sports", label:"Final Fixture — Coleng vs Coplant", image:"images/sports-14.png", desc:"Final fixture graphic for Coleng vs Coplant.", wide:false, tall:false },
  { id:"s15", cat:"sports", label:"Starting XI vs CYDASSA", image:"images/sports-15.png", desc:"Starting XI lineup announcement ahead of the CYDASSA clash.", wide:true, tall:false },
  { id:"s16", cat:"sports", label:"AERD Squad — NAAS", image:"images/sports-16.png", desc:"Official squad graphic for AERD — NAAS Tournament.", wide:false, tall:false },
  { id:"s17", cat:"sports", label:"Inter-Uni Novelty Football Match", image:"images/sports-17.png", desc:"Promotional design for the Inter-University Novelty Football Match.", wide:false, tall:false },
  { id:"s18", cat:"sports", label:"Travelling Squad Announcement", image:"images/sports-18.png", desc:"Travelling squad announcement card for away fixtures.", wide:false, tall:false },
  { id:"s19", cat:"sports", label:"FUNAAB 4–1 Crawford", image:"images/sports-19.png", desc:"Result graphic celebrating FUNAAB's 4–1 victory over Crawford.", wide:false, tall:false },
  { id:"s20", cat:"sports", label:"SUG Freshers Cup Draw", image:"images/sports-20.png", desc:"Official bracket draw graphic for the SUG Freshers Cup.", wide:true, tall:false },

  // Mockup Designs
  { id:"m01", cat:"mockup", label:"Injective Nigeria — Blue Tee", image:"images/mockup-01.png", desc:"Blue t-shirt mockup for Injective Nigeria — branded with the INJ logo and Nigerian flag mark.", wide:false, tall:false },
  { id:"m02", cat:"mockup", label:"Injective Nigeria — Black Tee", image:"images/mockup-02.png", desc:"Black t-shirt mockup for Injective Nigeria — clean dark colourway.", wide:false, tall:false },
  { id:"m03", cat:"mockup", label:"Injective Nigeria — Black Hoodie", image:"images/mockup-03.png", desc:"Black hoodie mockup for Injective Nigeria.", wide:false, tall:false },
  { id:"m04", cat:"mockup", label:"Injective Nigeria — Blue Hoodie", image:"images/mockup-04.png", desc:"Blue hoodie mockup for Injective Nigeria.", wide:false, tall:false },
  { id:"m05", cat:"mockup", label:"Injective Nigeria — Blue Sweatshirt", image:"images/mockup-05.png", desc:"Blue crewneck sweatshirt mockup for Injective Nigeria.", wide:false, tall:false },
  { id:"m06", cat:"mockup", label:"Injective Nigeria — Branded Bottle", image:"images/mockup-06.png", desc:"Black branded water bottle mockup for Injective Nigeria.", wide:false, tall:false },
  { id:"m07", cat:"mockup", label:"Injective Nigeria — Black Sweatshirt", image:"images/mockup-07.png", desc:"Black crewneck sweatshirt mockup for Injective Nigeria.", wide:false, tall:false },
  { id:"m08", cat:"mockup", label:"G-Spark White Tee — Side View", image:"images/mockup-08.png", desc:"G-Spark branded white t-shirt mockup — angled side view with flag accent.", wide:true, tall:false },
  { id:"m09", cat:"mockup", label:"G-Spark White Tee — Front", image:"images/mockup-09.png", desc:"G-Spark branded white t-shirt mockup — front-facing clean layout.", wide:false, tall:false },
  { id:"m10", cat:"mockup", label:"G-Spark Black Tee — Dark Mannequin", image:"images/mockup-10.png", desc:"G-Spark black t-shirt mockup on dark mannequin — bold contrast.", wide:false, tall:false },
  { id:"m11", cat:"mockup", label:"G-Spark Black Tee — Angled", image:"images/mockup-11.png", desc:"G-Spark black t-shirt on white mannequin — angled view showing full print.", wide:false, tall:false },
  { id:"m12", cat:"mockup", label:"Silent But Powerful — Black Tee", image:"images/mockup-12.png", desc:"'Silent But Powerful' streetwear tee for Aussmart Luxury — black colourway.", wide:true, tall:false },
  { id:"m13", cat:"mockup", label:"Silent But Powerful — White Tee", image:"images/mockup-13.png", desc:"'Silent But Powerful' streetwear tee for Aussmart Luxury — white colourway.", wide:false, tall:false },
  { id:"m14", cat:"mockup", label:"Dexpay — Community Tee (Angled)", image:"images/mockup-14.jpg", desc:"Dexpay community t-shirt mockup — illustrated characters border, angled view.", wide:false, tall:false },
  { id:"m15", cat:"mockup", label:"Giraffe Tower — Giraffish Tee", image:"images/mockup-15.jpg", desc:"Giraffe Tower 'Giraffish' white t-shirt — bold illustrated print.", wide:false, tall:false },
  { id:"m16", cat:"mockup", label:"Dexpay — Black Tee", image:"images/mockup-16.jpg", desc:"Dexpay black t-shirt mockup — clean logo placement with hexagon brand mark.", wide:true, tall:false },
  { id:"m17", cat:"mockup", label:"Giraffish — Trading Tee (Small Print)", image:"images/mockup-17.jpg", desc:"Giraffish 'Stop Trading Time for Money' tee — candlestick chart and character print.", wide:false, tall:false },
  { id:"m18", cat:"mockup", label:"Giraffish — Trading Tee (Bold Text)", image:"images/mockup-18.jpg", desc:"Giraffish 'Stop Trading Time for Money' — large bold typography front print.", wide:false, tall:false },
  { id:"m19", cat:"mockup", label:"Dexpay — White Tee", image:"images/mockup-19.jpg", desc:"Dexpay white t-shirt mockup — minimal brand mark and hexagon accent.", wide:false, tall:false },
  { id:"m20", cat:"mockup", label:"Dexpay — Community Tee (Front)", image:"images/mockup-20.jpg", desc:"Dexpay community t-shirt — front view with illustrated group and logo.", wide:true, tall:false }
];

// (patch: append web3 entries)
window.GALLERY_DATA = window.GALLERY_DATA.concat([
  // Web3 Designs
  { id:"w01", cat:"web3", label:"Bynomo — Litepaper is Live!", image:"images/web3-01.jpg", desc:"Launch announcement social post for Bynomo's litepaper going live — dark purple cinematic design.", wide:true, tall:false },
  { id:"w02", cat:"web3", label:"Bynomo — Eid Mubarak", image:"images/web3-02.jpg", desc:"Eid Mubarak greeting post for Bynomo — elegant mosque silhouette and clean typography.", wide:true, tall:false },
  { id:"w03", cat:"web3", label:"Bynomo — We Are Hiring!", image:"images/web3-03.jpg", desc:"Web3 recruitment post for Bynomo — Senior Solidity & Rust developer roles, dark grid aesthetic.", wide:true, tall:false },
  { id:"w04", cat:"web3", label:"Bynomo — Show Us, Don't Tell Us", image:"images/web3-04.jpg", desc:"Video creator challenge post for Bynomo — $100 reward campaign, glassmorphism cube design.", wide:true, tall:false },
  { id:"w05", cat:"web3", label:"Bynomo — Community Post", image:"images/web3-05.jpg", desc:"Social media community engagement design for Bynomo.", wide:false, tall:false },
  { id:"w06", cat:"web3", label:"Web3 Brand Design", image:"images/web3-06.png", desc:"Web3 brand social post design.", wide:false, tall:false },
  { id:"w07", cat:"web3", label:"Web3 Social Media Post", image:"images/web3-07.png", desc:"Bold social media design for a web3 brand.", wide:true, tall:false },
  { id:"w08", cat:"web3", label:"Web3 Announcement Graphic", image:"images/web3-08.png", desc:"Announcement graphic for a web3 project.", wide:false, tall:false },
  { id:"w09", cat:"web3", label:"Web3 Campaign Design", image:"images/web3-09.png", desc:"Campaign design for a web3 community.", wide:false, tall:false },
  { id:"w10", cat:"web3", label:"Web3 Community Post", image:"images/web3-10.png", desc:"Web3 community engagement social post.", wide:true, tall:false },
  { id:"w11", cat:"web3", label:"Web3 Brand Identity Post", image:"images/web3-11.jpg", desc:"Brand identity social post for a web3 project.", wide:false, tall:false },
  { id:"w12", cat:"web3", label:"Web3 Launch Graphic", image:"images/web3-12.jpg", desc:"Launch announcement visual for a web3 brand.", wide:false, tall:false },
  { id:"w13", cat:"web3", label:"Web3 Partnership Design", image:"images/web3-13.jpg", desc:"Partnership or collab announcement design for a web3 project.", wide:true, tall:false },
  { id:"w14", cat:"web3", label:"Web3 Event Post", image:"images/web3-14.jpg", desc:"Event or AMA promotional design for a web3 community.", wide:false, tall:false },
  { id:"w15", cat:"web3", label:"Web3 Milestone Post", image:"images/web3-15.jpg", desc:"Milestone or achievement celebration post for a web3 brand.", wide:false, tall:false },
  { id:"w16", cat:"web3", label:"Web3 Product Design", image:"images/web3-16.jpg", desc:"Product feature social post for a web3 platform.", wide:false, tall:false },
  { id:"w17", cat:"web3", label:"Web3 Update Graphic", image:"images/web3-17.jpg", desc:"Project update announcement graphic.", wide:true, tall:false },
  { id:"w18", cat:"web3", label:"Web3 Social Banner", image:"images/web3-18.jpg", desc:"Wide social media banner for a web3 project.", wide:true, tall:false },
  { id:"w19", cat:"web3", label:"Web3 Community Banner", image:"images/web3-19.jpg", desc:"Community-focused social banner design.", wide:true, tall:false },
  { id:"w20", cat:"web3", label:"Web3 Brand Post", image:"images/web3-20.jpg", desc:"Brand post design for a web3 crypto project.", wide:false, tall:false }
]);
